# Generated by Django 3.1.5 on 2021-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='species_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
